### PR TITLE
handle re-export too

### PR DESCRIPTION
**Pull request by jim-lake**
Handle re-export similar to import

### CODE REVIEW

**Comment by culler** [comment]
@jim-lake This looks fine to me but I would like to be able to test it.  Do you know of a standard library that I would be able to find on my system which reexports symbols?

**Comment by jim-lake** [comment]
/usr/lib/libSystem.B.dylib

**Comment by culler** [comment]
That library has not been accessible from the filesystem since macOS 11.  You can only run macher on files in the filesystem.  However, it turns out that XCode includes an actual libSystem.B.dylib inside the watchOS SDK.  So I was able to test on that.

**Comment by culler** [comment]
@jim-lake: Thanks for making a contribution to macher.  I have released version 1.5 which includes your improvement.

**Pull request merged**
